# Generated by Django 4.2 on 2024-02-29 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname')),
                ('email', models.EmailField(max_length=100, verbose_name='Emai')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start')),
                ('end_time', models.DateTimeField(verbose_name='end')),
                ('send_time', models.TimeField(default=datetime.time(18, 30), verbose_name='Send time')),
                ('frequency', models.CharField(choices=[('ONCE_A_DAY', 'once a day '), ('ONCE_A_WEEK', 'once a week'), ('ONCE_A_MONTH', 'once a month')], verbose_name='Frequency')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('COMPLETE', 'complete'), ('RUNING', 'runing')], verbose_name='Status')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=200, verbose_name='Title')),
                ('message_text', models.TextField(verbose_name='Message text')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'success'), ('FAILURE', 'failure')], null=True, verbose_name='Status')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Server Response')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='main.mail', verbose_name='Mail')),
            ],
        ),
    ]
